# -*- coding: utf-8 -*-
"""Assigment_1_Machine_Learning_Fatma_Okasha_251000148.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n4jwb1sf8Fac6IMXZPN2nDhLAlowd-ZO
"""

import math
import matplotlib.pyplot as plt
# --------------------Reading data from the file--------------------
def load_data(filename):
    '''
     load the data from the text file
    '''
    f = open(filename, 'r')
    text = f.read()
    f.close()
    parts = text.split()
    data = []
    for x in parts:
        data.append(float(x))
    return data

data = load_data("EnhancedData.txt")
print(data)

# ---------( BEFORE REMOVAL OUTLIER) Basic Statistical Measures (Mean, Median)--------------------
print("--------------------------BEFORE REMOVAL OUTLIER-----------------")

def calculate_mean(data):
    '''
      Calculate mean of the data
     '''

    return sum(data) / len(data)

print("mean of the data =  ",calculate_mean(data))

def calculate_median(data):
    '''
     Calculate median of the data
     sort the data and if len(data) is even   take avg of 2 middle elements
     else if it is odd -->   median is len(data)/2 the middle element
    '''

    sorted_data = sorted(data)
    n = len(sorted_data)
    if n %2 ==0 :
        return ( sorted_data[n//2] + sorted_data[(n//2)-1] ) / 2
    else :
        return sorted_data[(n//2)]

print("median of the data  =  ", calculate_median(data))

# ---------( BEFORE REMOVAL OUTLIER) Basic Statistical Measures (Standard Deviation, and Variance) --------------------------
def calculate_variance(data):
    '''
      Calculate Variance of the data =
      sum(X(i)-mean)^2 / len(data)
     '''
    n = len(data)
    total=0.0
    mean = sum(data) / len(data)
    for  num in data:
        total += (num-mean)**2
    return  total/ n

print("variance of the data = ", calculate_variance(data))

def calculate_standard_deviation(data):
    '''
        Calculate standard deviation of the data =
        sqrt(variance)
    '''

    return  calculate_variance(data)**0.5

print("Standard Deviation of the data = ", calculate_standard_deviation(data))

def calculate_mode(data):
    """
    Return the most frequent value in the data.
    """
    return max(data, key=data.count)

print("Mode of data:", calculate_mode(data))

# --------------------Quartile Values and IQR(Q1,Q2,Q3,IQR)--------------------
# [3,5,6,8,10,11,12,14,15,18,26]  q1=6 , q2=11 , q3 =15   // n is  odd
# [8,11,13,17,19,21,23,26,29,31,35,54]   q1=(13+17)/2  q2 = (21+23)/2  q3 = (29+31)/2   // n is  even

def calculate_quartiles(data):
    """
       Compute the first quartile (Q1), median (Q2), third quartile (Q3),
       and interquartile range (IQR) of a dataset.

       The function sorts the data, splits it into lower and upper halves
       (handling even and odd lengths), computes Q1 and Q3 using the median,
       and returns Q1, Q2, Q3, and IQR.
       """


    n= len(data)
    sorted_data= sorted(data)
    q2=calculate_median(data)

    if n%2 ==0 :
        q1_list=sorted_data[0:n//2]
        q3_list = sorted_data[n//2 :]

    else:

        index_of_median_element= sorted_data.index(q2)
        q1_list=sorted_data[0:index_of_median_element]
        q3_list = sorted_data[index_of_median_element+1:]

    q1 = calculate_median(q1_list)
    q3 = calculate_median(q3_list)
    iqr = q3-q1

    return  q1,q2,q3,iqr


print("Q1, Q2, Q3 and IQR of  data = ", calculate_quartiles(data))
q1,q2,q3,iqr = calculate_quartiles(data)

# --------------------Outlier Detection, Scoring, and Classification:--------------------
# Outlier bounds:
# Lower bound = Q1 - 1.5 * IQR
# Upper bound = Q3 + 1.5 * IQR


def detect_outliers(data,q1,q3,iqr):
  """
    Identify outliers in the dataset using the IQR method.

    The function
    1- computes lower and upper bounds (Q1 − 1.5×IQR, Q3 + 1.5×IQR),
    2- checks which values fall outside these bounds ,
    3- calculates an outlier score
    4- classifies each outlier as  Moderate, High, or Extreme.
    5- Returns a list of [value, score, level].
    """

  lower_bound_outlier = q1 - 1.5 * iqr
  upper_bound_outlier = q3 + 1.5* iqr

  outliers_list=[]

  for  num in data :
      if num < lower_bound_outlier or num > upper_bound_outlier :
          if num  >  upper_bound_outlier :
              outlier_score= (num - q3) / iqr
          else :
              outlier_score = (q1 - num) / iqr

          if outlier_score > 1.5 and outlier_score < 3 :
              level = "Moderate"

          elif outlier_score > 3 and outlier_score < 5 :
              level = "High"

          elif outlier_score > 5 :
              level = "Extreme"

          # a list of [value, score, level].
          outliers_list.append([num,outlier_score,level])

  # print(len(outliers_list))
  # print(len(data))

  return outliers_list



outliers_list= detect_outliers(data,q1,q3,iqr)
print("outliers are  ", detect_outliers(data,q1,q3,iqr))

# --------------------Removing outliers level by level-------------------

def remove_outlier_progressive(outliers_list):
    # Moderate / High / Extreme
    # idx(0) --> number(element in data) , idx(1) --> score , idx(2) --> level
    """
      Remove outliers from the dataset in progressive stages (Moderate → High → Extreme),
      recalculating  statistics after remove each stage

      For each outlier level, the function removes all values of that level from a copy
      of the dataset, then computes the mean, median, and standard deviation of the
      remaining data. It returns a dictionary containing these statistics for each
      removal stage.
      """

    statistics_analysis={}
    dataset = data.copy()
    # print(len(dataset))
    # print(len(data))

    # Moderate outliers removal
    moderate_dataset = data.copy()
    for item in outliers_list:
        if item[2] == "Moderate":
            moderate_dataset.remove(item[0])

    statistics_analysis["Moderate"] = {
        "mean": calculate_mean(moderate_dataset),
        "median": calculate_median(moderate_dataset),
        "std": calculate_standard_deviation(moderate_dataset),
        # "quartiles": calculate_quartiles(moderate_dataset),
        # "variance": calculate_variance(moderate_dataset)
    }

    # High outliers removal
    high_dataset = moderate_dataset.copy()
    for item in outliers_list:
        if item[2] == "High":
            high_dataset.remove(item[0])

    statistics_analysis["High"] = {
        "mean": calculate_mean(high_dataset),
        "median": calculate_median(high_dataset),
        "std": calculate_standard_deviation(high_dataset),
        # "quartiles": calculate_quartiles(high_dataset),
        # "variance": calculate_variance(high_dataset)
    }

    # Extreme outliers removal
    extreme_dataset = high_dataset.copy()
    for item in outliers_list:
        if item[2] == "Extreme":
            extreme_dataset.remove(item[0])

    statistics_analysis["Extreme"] = {
        "mean": calculate_mean(extreme_dataset),
        "median": calculate_median(extreme_dataset),
        "std": calculate_standard_deviation(extreme_dataset),
        # "quartiles": calculate_quartiles(extreme_dataset),
        # "variance": calculate_variance(extreme_dataset)

    }

    return  statistics_analysis


statistics_results = remove_outlier_progressive(outliers_list)
print("removing outliers and re calculate statistics ", statistics_results)

# Mean: Decreases gradually as more extreme values are removed. This shows that outliers skew the average upward.
# Median: Stays relatively stable, even with moderate and high outliers
# Standard Deviation: Drops sharply after removing high and extreme outliers, indicating that spread of the data is large  by extreme values.

# --------------------------Histogram and Box Plot(original data) ----------------------------------------
def display_hist_original(data):
    """
    diplay histogram of original data
    """

    plt.hist(data)
    plt.title("Histogram (Original Data)")
    plt.show()

display_hist_original(data)

def display_boxplot_original(data):
    """
      diplay boxplot of original data
      """
    plt.boxplot(data)
    plt.title("Box Plot(Original Data)")
    plt.show()

display_boxplot_original(data)

#-------------------Outlier Removal Impact(histogram , boxplot) after removal----------------------------------
def display_hist_boxplot_after_removal_outlier(outliers_list):
    """
    Display histogram and boxplot side by side for each outlier removal level.
    Each level gets its own row: histogram on left, boxplot on right.
    """
    dataset = data.copy()
    levels = ["Moderate", "High", "Extreme"]

     # Make the figure taller
    plt.figure(figsize=(12, 12))

    for i, level in enumerate(levels):
        # Remove outliers of current level

       # This  store all items that are NOT outliers
        filtered = []

        for x in dataset:
            keep = True
            for o in outliers_list:
                # Check if  item matches  outlier (same value and same level)
                if x == o[0] and level == o[2]:
                  # Mark it  to remove it
                    keep = False
                    break

            if keep:
                filtered.append(x)

        dataset = filtered

        print(f"Length after removing {level} outliers: {len(dataset)}")

        # Histogram
        plt.subplot(len(levels), 2, 2*i + 1)
        plt.hist(dataset, bins=20, color='skyblue', edgecolor='black')
        plt.title(f'{level} Outliers Removed - Histogram')
        plt.xlabel('Value')
        plt.ylabel('Frequency')

        # Boxplot
        # Make subplot with one row per level, two columns, and place the box in  second column
        plt.subplot(len(levels), 2, 2*i + 2)
        plt.boxplot(dataset)
        plt.title(f'{level} Outliers Removed - Boxplot')

    # Handle spacing as plots don’t overlap
    plt.tight_layout()
    plt.show()
    # return dataset


display_hist_boxplot_after_removal_outlier(outliers_list)

# print(dataset["Moderate"])  # Dataset after Moderate removal
# print(dataset["High"])      # Dataset after High removal
# print(dataset["Extreme"])   # Dataset after Extreme removal

#---------------------a line plot to show the change in mean, median, and standard deviation as each outlier level------------------------
def plot_statistics_progressive(statistics_analysis):
    """
    Plot the change in mean, median, and standard deviation
    as outliers are progressively removed (Moderate → High → Extreme).

     parameters are statistics_analysis : dict
     Dictionary returned by remove_outlier_progressive()
     keys : outlier levels and values : mean, median, and std.

    """
    # print(statistics_analysis)

    levels = list(statistics_analysis.keys())
    means_list = [statistics_analysis[level]["mean"] for level in levels]

    medians_list = [statistics_analysis[level]["median"] for level in levels]
    stds_list = [statistics_analysis[level]["std"] for level in levels]

    # plt.figure(figsize=(6, 6))
    plt.plot(levels, means_list , label='Mean')
    plt.plot(levels, medians_list, label='Median')
    plt.plot(levels,  stds_list, label='Standard Deviation')

    plt.xlabel("Outlier Removal Level")
    plt.ylabel("Value")
    plt.title("Change in Mean, Median, and Standard Deviation After Outlier Removal")
    plt.legend()
    plt.grid(True)
    plt.show()
  # statistics_results is  return of function remove_outlier_progressive(outliers_list)
plot_statistics_progressive(statistics_results)